add oak
parallel-finance/auction-toolkit pull request #192
Opened 2022-09-09 19:15 UTC by justinzhou93

## Onboarding issue link

* Before request the review, please open an issue based on the [onBoarding template](./ISSUE_TEMPLATE/onborading.md);
* Provide link to the onBoarding issue

2022-09-10 00:45 UTC, irsal requested changes

2022-09-10 00:45 UTC, irsal commented on crowdloans/projects/polkadot.json
> +    "paraid": "2090",
this is not locked in yet

2022-09-10 00:45 UTC, irsal commented on crowdloans/projects/polkadot.json
> +    "name": "Oak Network",
`OAK Network`

2022-09-10 00:45 UTC, irsal commented on crowdloans/projects/polkadot.json
> +    "overview": "Oak is an automation blockchain for Defi and recurring payments across protocols. Oak aims to be the best-in-class automation utility across protocols, offering on-chain automation n
`OAK delivers trustless automation, dedicating its block space and optimizing gas to store, trigger, and execute transactions on connected blockchains.`

2022-09-10 00:45 UTC, irsal commented on crowdloans/rewards/polkadot.json
> +          "Referral: Reward 10% of receivers' base split between sender and receiver",
technically referral won't be available through the parallel app

2022-09-10 00:45 UTC, irsal commented on crowdloans/rewards/polkadot.json
> +        "label": "Bonus",
I'd add 4 PARA and cDot, see: https://oak.tech/oak/reward/#base-reward

2022-09-10 00:45 UTC, irsal commented on crowdloans/rewards/polkadot.json
> +        "label": "Vesting schedule",
is this specifically for the crowdloan rewards?

2022-09-13 05:14 UTC, justinzhou93 commented on crowdloans/projects/polkadot.json
> +    "paraid": "2090",
should be locked now: 2090

2022-09-13 05:23 UTC, irsal requested changes
more feedback

2022-09-13 05:23 UTC, irsal commented on crowdloans/rewards/polkadot.json
> +        "content": ["Up to 150,000,000 OAK (15% of total token supply)"]
1.5%

2022-09-13 05:23 UTC, irsal commented on crowdloans/rewards/polkadot.json
> +          "Parallel Bonus: 4 PARA and 1 cDot."
per DOT contributed

2022-09-13 14:53 UTC, irsal approved these changes
lgtm from the oak side

2022-09-14 02:28 UTC, crystalynliu approved these changes
LGTM

2022-09-14 02:43 UTC, justinzhou93 commented
hey @crystalynliu , sorry but would you mind re-lgtm'ing again? there was a merge conflict

2022-09-14 02:56 UTC, crystalynliu approved these changes

2022-09-14 02:56 UTC, merged